# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
#  secret_key_base: 497149f257324ba8da60f8d9793d0d88f8b6cc888054f543f1581966bab25f2147805abdc6da2543e9f0e50ceb36238c77cf2011998b9ab5419c6b951d67f95b
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: 5427f2b4c93a5a4cb2ed17c1195be0759d7656a9d035afdf4efcf390a487f5791aad2f9d25c0f69f70bbb1690b974defb154e2a2ddde7c567f564629738b1f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
