aws:
  access_key: ''
  secret_access_key: ''

auth:
  facebook:
    id: ''
    secret: ''
  google:
    id: ''
    secret: ''
  twitter:
    id: ''
    secret: ''

adsense:
  client: 'development-localhost'

elasticsearch:
  host: 'localhost:9200'

slack:
  feedback:
    webhook_url: "https://test.me/webhook_url"
  error:
    webhook_url: "https://test.me/webhook_url"

gtm:
  id: ""

crypt:
  secret: "hogeoghohohgeohgoehgoehgoehgoehgo"
